version: "3"
services:
  db:
    container_name: 'aqua_postgres'
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_PWD}
      -  POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5430:5432"
    volumes:
      - ~/aquaPGdata:/var/lib/postgresql/data/

  redis:
    container_name: "aqua_redis"
    image: redis
    ports:
      - "6377:6379"

  mqtt:
    container_name: "mqtt"
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ~/mosquitto:/mosquitto
      - ~/mosquitto/data:/mosquitto/data
      - ~/mosquitto/log:/mosquitto/log

  backend:
    container_name: "aquaVisual"
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8860:8860"
    command:
      - bash
      - -c
      - |
        python3 manage.py migrate
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py collectstatic --no-input
        exec python3 manage.py runserver 0.0.0.0:8860
